  const items = [
  {
    itemID: 1,
    name: "Coins",
    image: "../assets/ItemThumbnail/Div/Coins.png",
    price: 1,
    haPrice: 0,
    description: "Coins!",
    type: "",
    prodTimer: null,
    prodExp: null,
    skill: ""
  },
  {
    itemID: 2,
    name: "Normal Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Normal_Log.png',
    price: 4,
    haPrice: 1,
    description: "Just normal logs.",
    type: "woodcutting",
    prodTimer: 1.5,
    prodExp: 15,
    skill: "Woodcutting"
  },
  {
    itemID: 3,
    name: "Oak logs",
    image: '../assets/ItemThumbnail/Woodcutting/Oak_Log.png',
    price: 8,
    haPrice: 3,
    description: "Pile of oak logs.",
    type: "woodcutting",
    prodTimer: 2,
    prodExp: 25,
    skill: "Woodcutting"
  },
  {
    itemID: 4,
    name: "Willow Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Willow_Log.png',
    price: 12,
    haPrice: 5,
    description: "Pile of willow logs.",
    type: "woodcutting",
    prodTimer: 3,
    prodExp: 40,
    skill: "Woodcutting"
  },
  {
    itemID: 5,
    name: "Maple Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Maple_Log.png',
    price: 16,
    haPrice: 8,
    description: "Pile of maple logs.",
    type: "woodcutting",
    prodTimer: 3.5,
    prodExp: 60,
    skill: "Woodcutting"
  },
  {
    itemID: 6,
    name: "Yew Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Yew_Log.png',
    price: 20,
    haPrice: 12,
    description: "Pile of yew logs.",
    type: "woodcutting",
    prodTimer: 5,
    prodExp: 75,
    skill: "Woodcutting"
  },
  {
    itemID: 7,
    name: "Magic Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Magic_Log.png',
    price: 30,
    haPrice: 15,
    description: "Pile of magic logs.",
    type: "woodcutting",
    prodTimer: 6,
    prodExp: 90,
    skill: "Woodcutting"
  },
  {
    itemID: 8,
    name: "Elder Logs",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 40,
    haPrice: 20,
    description: "Pile of elder logs.",
    type: "woodcutting",
    prodTimer: 8,
    prodExp: 120,
    skill: "Woodcutting"
  },
  {
    itemID: 9,
    name: "Shrimp",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 4,
    haPrice: 1,
    description: "A stack of shrimp, you should cook it.",
    type: "fishing",
    prodTimer: 2,
    prodExp: 15,
    skill: "Fishing"
  },
  {
    itemID: 10,
    name: "Herring",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 6,
    haPrice: 2,
    description: "A herring, you should cook it.",
    type: "fishing",
    prodTimer: 2.5,
    prodExp: 25,
    skill: "Fishing"
  },
  {
    itemID: 11,
    name: "Trout",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 10,
    haPrice: 5,
    description: "A trout, you should cook it.",
    type: "fishing",
    prodTimer: 1.5,
    prodExp: 20,
    skill: "Fishing"
  },
  {
    itemID: 12,
    name: "Pike",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 15,
    haPrice: 8,
    description: "A pike, you should cook it.",
    type: "fishing",
    prodTimer: 3,
    prodExp: 45,
    skill: "Fishing"
  },
  {
    itemID: 13,
    name: "Lobster",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 20,
    haPrice: 10,
    description: "A lobster, you should cook it.",
    type: "fishing",
    prodTimer: 5,
    prodExp: 75,
    skill: "Fishing"
  },
  {
    itemID: 14,
    name: "Swordfish",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 30,
    haPrice: 15,
    description: "A swordfish, you should cook it.",
    type: "fishing",
    prodTimer: 4,
    prodExp: 60,
    skill: "Fishing"
  },
  {
    itemID: 15,
    name: "Shark",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 40,
    haPrice: 25,
    description: "A shark, you should cook it.",
    type: "fishing",
    prodTimer: 6,
    prodExp: 100,
    skill: "Fishing"
  },
  {
    itemID: 16,
    name: "Manta Ray",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 50,
    haPrice: 30,
    description: "A manta ray, you should cook it.",
    type: "fishing",
    prodTimer: 6,
    prodExp: 120,
    skill: "Fishing"
  },
  {
    itemID: 17,
    name: "Dark Crab",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 60,
    haPrice: 40,
    description: "A dark crab, you should cook it.",
    type: "fishing",
    prodTimer: 8,
    prodExp: 150,
    skill: "Fishing"
  },
  {
    itemID: 18,
    name: "Tin Ore",
    image: '../assets/ItemThumbnail/Mining/Tin_Ore.png',
    price: 5,
    haPrice: 1,
    description: "Pile of Tin Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 3,
    prodExp: 20,
    skill: "Mining"
  },
  {
    itemID: 19,
    name: "Copper Ore",
    image: '../assets/ItemThumbnail/Mining/Copper_Ore.png',
    price: 5,
    haPrice: 1,
    description: "Pile of Copper Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 3,
    prodExp: 20,
    skill: "Mining"
  },
  {
    itemID: 20,
    name: "Iron Ore",
    image: '../assets/ItemThumbnail/Mining/Iron_Ore.png',
    price: 10,
    haPrice: 6,
    description: "Pile of Iron Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 1.5,
    prodExp: 15,
    skill: "Mining"
  },
  {
    itemID: 21,
    name: "Coal Ore",
    image: '../assets/ItemThumbnail/Mining/Coal_Ore.png',
    price: 20,
    haPrice: 10,
    description: "Pile of Coal Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 5,
    prodExp: 45,
    skill: "Mining"
  },
  {
    itemID: 22,
    name: "Silver Ore",
    image: '../assets/ItemThumbnail/Mining/Silver_Ore.png',
    price: 20,
    haPrice: 10,
    description: "Pile of Silver Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 4,
    prodExp: 40,
    skill: "Mining"
  },
  {
    itemID: 23,
    name: "Gold Ore",
    image: '../assets/ItemThumbnail/Mining/Gold_Ore.png',
    price: 30,
    haPrice: 20,
    description: "Pile of Gold Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 5,
    prodExp: 55,
    skill: "Mining"
  },
  {
    itemID: 24,
    name: "Mithril Ore",
    image: '../assets/ItemThumbnail/Mining/Mithril_Ore.png',
    price: 40,
    haPrice: 25,
    description: "Pile of Mithril Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 7,
    prodExp: 80,
    skill: "Mining"
  },
  {
    itemID: 25,
    name: "Adamant Ore",
    image: '../assets/ItemThumbnail/Mining/Adamant_Ore.png',
    price: 50,
    haPrice: 35,
    description: "Pile of Adamant Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 8,
    prodExp: 90,
    skill: "Mining"
  },
  {
    itemID: 26,
    name: "Rune Ore",
    image: '../assets/ItemThumbnail/Mining/Rune_Ore.png',
    price: 70,
    haPrice: 50,
    description: "Pile of Rune Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 10,
    prodExp: 150,
    skill: "Mining"
  },
  {
    itemID: 27,
    name: "Dragon Ore",
    image: '../assets/ItemThumbnail/Mining/Dragon_Ore.png',
    price: 120,
    haPrice: 100,
    description: "Pile of Dragon Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 12,
    prodExp: 200,
    skill: "Mining"
  },
  {
    itemID: 28,
    name: "Bronze Bar",
    image: '../assets/ItemThumbnail/Smithing/Bronze_Bar.png',
    price: 20,
    haPrice: 10,
    description: "A solid Bronze Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 10,
    skill: "Smithing"
  },
  {
    itemID: 29,
    name: "Iron Bar",
    image: '../assets/ItemThumbnail/Smithing/Iron_Bar.png',
    price: 30,
    haPrice: 20,
    description: "A solid Iron Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 15,
    skill: "Smithing"
  },
  {
    itemID: 30,
    name: "Steel Bar",
    image: '../assets/ItemThumbnail/Smithing/Steel_Bar.png',
    price: 45,
    haPrice: 30,
    description: "A solid Steel Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 25,
    skill: "Smithing"
  },
  {
    itemID: 31,
    name: "Silver Bar",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 30,
    haPrice: 25,
    description: "A solid Silver Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 15,
    skill: "Smithing"
  },
  {
    itemID: 32,
    name: "Gold Bar",
    image: '../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 45,
    haPrice: 35,
    description: "A solid Gold Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 25,
    skill: "Smithing"
  },
  {
    itemID: 33,
    name: "Mithril Bar",
    image: '../assets/ItemThumbnail/Smithing/Mithril_Bar.png',
    price: 100,
    haPrice: 60,
    description: "A solid Mithril Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 35,
    skill: "Smithing"
  },
  {
    itemID: 34,
    name: "Adamant Bar",
    image: '../assets/ItemThumbnail/Smithing/Adamant_Bar.png',
    price: 200,
    haPrice: 140,
    description: "A solid Adamant Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 45,
    skill: "Smithing"
  },
  {
    itemID: 35,
    name: "Rune Bar",
    image: '../assets/ItemThumbnail/Smithing/Rune_Bar.png',
    price: 400,
    haPrice: 320,
    description: "A solid Rune Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 36,
    name: "Dragon Bar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A solid Dragon Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 80,
    skill: "Smithing"
  },
  {
    itemID: 37,
    name: "Bronze Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 10,
    haPrice: 5,
    description: "A Bronze knife, can be worn in a weapon slot. Try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 38,
    name: "Bronze med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 12,
    haPrice: 6,
    description: "A solid Dragon Bar, you should try smithing it into something nice!",
    type: "Helm",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 39,
    name: "Bronze Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 15,
    haPrice: 7,
    description: "A Bronze sword, can be worn in a weapon slot. Try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 40,
    name: "Bronze Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 2,
    haPrice: 1,
    description: "A Bronze Bolts, you should try fletching them into bolts!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 41,
    name: "Bronze Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 18,
    haPrice: 10,
    description: "A Bronze Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 42,
    name: "Bronze Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 16,
    haPrice: 10,
    description: "A Bronze Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 43,
    name: "Bronze Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 2,
    haPrice: 1,
    description: "A Bronze Arrow Tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 20,
    skill: "Smithing"
  },
  {
    itemID: 44,
    name: "Bronze Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 20,
    haPrice: 10,
    description: "A Bronze Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 40,
    skill: "Smithing"
  },
  {
    itemID: 45,
    name: "Bronze Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 3,
    haPrice: 2,
    description: "A Bronze Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 40,
    skill: "Smithing"
  },
  {
    itemID: 46,
    name: "Bronze Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 20,
    haPrice: 12,
    description: "A Bronze Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 40,
    skill: "Smithing"
  },
  {
    itemID: 47,
    name: "Bronze Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 20,
    haPrice: 12,
    description: "A Bronze Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 40,
    skill: "Smithing"
  },
  {
    itemID: 48,
    name: "Bronze Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 25,
    haPrice: 15,
    description: "A Bronze Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 40,
    skill: "Smithing"
  },
  {
    itemID: 49,
    name: "Bronze Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 30,
    haPrice: 15,
    description: "A Bronze Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 50,
    name: "Bronze Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 40,
    haPrice: 20,
    description: "A Bronze Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 51,
    name: "Bronze 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 40,
    haPrice: 20,
    description: "A Bronze 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 52,
    name: "Bronze Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 55,
    haPrice: 25,
    description: "A Bronze Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 53,
    name: "Bronze Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 55,
    haPrice: 25,
    description: "A Bronze Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 54,
    name: "Bronze Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 75,
    haPrice: 35,
    description: "A Bronze Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 100,
    skill: "Smithing"
  },
  {
    itemID: 55,
    name: "Iron Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 20,
    haPrice: 10,
    description: "A Iron Knife, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 56,
    name: "Iron med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 25,
    haPrice: 10,
    description: "A Iron med Helm, you should try it on!",
    type: "Helm",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 57,
    name: "Iron Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 25,
    haPrice: 10,
    description: "A Iron Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 58,
    name: "Iron Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 4,
    haPrice: 2,
    description: "A Iron Bolts, you should try fletching them into bolts!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 59,
    name: "Iron Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 40,
    haPrice: 20,
    description: "A Iron Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 60,
    name: "Iron Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 45,
    haPrice: 40,
    description: "A Iron Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 61,
    name: "Iron Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 5,
    haPrice: 2,
    description: "Some Iron Arrow Tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 30,
    skill: "Smithing"
  },
  {
    itemID: 62,
    name: "Iron Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 60,
    haPrice: 25,
    description: "A Iron Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 63,
    name: "Iron Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 5,
    haPrice: 2,
    description: "Some Iron Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 64,
    name: "Iron Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 80,
    haPrice: 40,
    description: "A Iron Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 65,
    name: "Iron Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 90,
    haPrice: 40,
    description: "A Iron Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 60,
    skill: "Smithing"
  },
  {
    itemID: 66,
    name: "Iron Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 100,
    haPrice: 45,
    description: "A Iron Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 67,
    name: "Iron Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 120,
    haPrice: 60,
    description: "A Iron Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 68,
    name: "Iron Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 140,
    haPrice: 70,
    description: "A Iron Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 69,
    name: "Iron 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 140,
    haPrice: 70,
    description: "A Iron 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 70,
    name: "Iron Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 160,
    haPrice: 70,
    description: "A Iron Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 71,
    name: "Iron Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 160,
    haPrice: 70,
    description: "A Iron Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 72,
    name: "Iron Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 180,
    haPrice: 120,
    description: "A Iron Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 73,
    name: "Steel Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Knife, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 74,
    name: "Steel med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel med Helm, you should try it on!",
    type: "Helm",
    prodTimer: 2,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 75,
    name: "Steel Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Sword, you should try it on!",
    type: "weapon",
    prodTimer: 2,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 76,
    name: "Steel Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Bolts, you should try fletching them into bolts",
    type: "fletching",
    prodTimer: 4,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 77,
    name: "Steel Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 100,
    skill: "Smithing"
  },
  {
    itemID: 78,
    name: "Steel Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 79,
    name: "Steel Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Arrow Tips, you should try flecthing them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 80,
    name: "Steel Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 100,
    skill: "Smithing"
  },
  {
    itemID: 81,
    name: "Steel Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 50,
    skill: "Smithing"
  },
  {
    itemID: 82,
    name: "Steel Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 100,
    skill: "Smithing"
  },
  {
    itemID: 83,
    name: "Steel Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 100,
    skill: "Smithing"
  },
  {
    itemID: 84,
    name: "Steel Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 85,
    name: "Steel Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 86,
    name: "Steel Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 87,
    name: "Steel 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 2,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 88,
    name: "Steel Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 89,
    name: "Steel Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 150,
    skill: "Smithing"
  },
  {
    itemID: 90,
    name: "Steel Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Steel Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 250,
    skill: "Smithing"
  },
  {
    itemID: 91,
    name: "Mithril Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Knife, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 92,
    name: "Mithril med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril med Helm, you should try it on!",
    type: "helm",
    prodTimer: 2,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 93,
    name: "Mithril Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 94,
    name: "Mithril Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Bolts, you should try fletching them into bolts!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 95,
    name: "Mithril Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 140,
    skill: "Smithing"
  },
  {
    itemID: 96,
    name: "Mithril Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 97,
    name: "Mithril Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Arrow Tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 98,
    name: "Mithril Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 140,
    skill: "Smithing"
  },
  {
    itemID: 99,
    name: "Mithril Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 70,
    skill: "Smithing"
  },
  {
    itemID: 100,
    name: "Mithril Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 2,
    prodExp: 140,
    skill: "Smithing"
  },
  {
    itemID: 101,
    name: "Mithril Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 140,
    skill: "Smithing"
  },
  {
    itemID: 101,
    name: "Mithril Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 102,
    name: "Mithril Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 103,
    name: "Mithril Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 104,
    name: "Mithril 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 105,
    name: "Mithril Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Mithril Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 106,
    name: "Mithril Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 210,
    skill: "Smithing"
  },
  {
    itemID: 107,
    name: "Mithril Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Mithril Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 350,
    skill: "Smithing"
  },
  {
    itemID: 108,
    name: "Adamant Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Knife, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 109,
    name: "Adamant med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant med Helm, you should try it on!",
    type: "helm",
    prodTimer: 2,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 110,
    name: "Adamant Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Sword, you should try it on!",
    type: "weapon",
    prodTimer: 2,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 111,
    name: "Adamant Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Adamant Platebody, you should try fletching them into bolts!",
    type: "fletching",
    prodTimer: 2,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 112,
    name: "Adamant Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 180,
    skill: "Smithing"
  },
  {
    itemID: 113,
    name: "Adamant Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 114,
    name: "Adamant Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Adamant Arrow Tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 115,
    name: "Adamant Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 180,
    skill: "Smithing"
  },
  {
    itemID: 116,
    name: "Adamant Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Adamant Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 90,
    skill: "Smithing"
  },
  {
    itemID: 117,
    name: "Adamant Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 180,
    skill: "Smithing"
  },
  {
    itemID: 118,
    name: "Adamant Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 180,
    skill: "Smithing"
  },
  {
    itemID: 119,
    name: "Adamant Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 120,
    name: "Adamant Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 121,
    name: "Adamant Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 122,
    name: "Adamant 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 123,
    name: "Adamant Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 124,
    name: "Adamant Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 270,
    skill: "Smithing"
  },
  {
    itemID: 125,
    name: "Adamant Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Adamant Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 450,
    skill: "Smithing"
  },
  {
    itemID: 126,
    name: "Rune Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Knife, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 127,
    name: "Rune med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune med Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 128,
    name: "Rune Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 129,
    name: "Rune Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Rune Bolts, you should try fletching them into some rune bolts!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 130,
    name: "Rune Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Scimitar, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 240,
    skill: "Smithing"
  },
  {
    itemID: 131,
    name: "Rune Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Spear, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 132,
    name: "Rune Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Arrow Tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 133,
    name: "Rune Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Longsword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 240,
    skill: "Smithing"
  },
  {
    itemID: 134,
    name: "Rune Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Rune Javelin Heads, you should try fletching them into javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 120,
    skill: "Smithing"
  },
  {
    itemID: 135,
    name: "Rune Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 240,
    skill: "Smithing"
  },
  {
    itemID: 136,
    name: "Rune Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Square Shield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 240,
    skill: "Smithing"
  },
  {
    itemID: 137,
    name: "Rune Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Battleaxe, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 138,
    name: "Rune Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 139,
    name: "Rune Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Kiteshield, you should try it on!",
    type: "shield",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 140,
    name: "Rune 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune 2H Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 141,
    name: "Rune Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Rune Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 142,
    name: "Rune Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 360,
    skill: "Smithing"
  },
  {
    itemID: 143,
    name: "Rune Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Rune Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 600,
    skill: "Smithing"
  },
  {
    itemID: 144,
    name: "Dragon Knife",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Knife, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 145,
    name: "Dragon med Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon med Helm, something to cover your fragile little head!",
    type: "helm",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 146,
    name: "Dragon Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Sword, you should try it on!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 147,
    name: "Dragon Bolts",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Dragon Bolts, you should try fletching them to some bolts!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 148,
    name: "Dragon Scimitar",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Scimitar, slice them like watermelons!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 320,
    skill: "Smithing"
  },
  {
    itemID: 149,
    name: "Dragon Spear",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Spear, a big red stabby thing!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 150,
    name: "Dragon Arrow Tips",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Dragon Arrow tips, you should try fletching them into arrows!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 151,
    name: "Dragon Longsword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Longsword, you should try it on, it has a mean stab!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 320,
    skill: "Smithing"
  },
  {
    itemID: 152,
    name: "Dragon Javelin Heads",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Some Dragon Javelin Heads, you should try fletching it to javelins!",
    type: "fletching",
    prodTimer: 4,
    prodExp: 160,
    skill: "Smithing"
  },
  {
    itemID: 153,
    name: "Dragon Full Helm",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Full Helm, you should try it on!",
    type: "helm",
    prodTimer: 4,
    prodExp: 320,
    skill: "Smithing"
  },
  {
    itemID: 154,
    name: "Dragon Square Shield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Square Shield. Look, its square!",
    type: "shield",
    prodTimer: 4,
    prodExp: 320,
    skill: "Smithing"
  },
  {
    itemID: 155,
    name: "Dragon Battleaxe",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Battleaxe, what a scary weapon!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 156,
    name: "Dragon Chainbody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Chainbody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 157,
    name: "Dragon Kiteshield",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Kiteshield, such a big shield!",
    type: "shield",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 158,
    name: "Dragon 2H Sword",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon 2H Sword, it has a heavy swing!",
    type: "weapon",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 159,
    name: "Dragon Platelegs",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "Dragon Platelegs, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 160,
    name: "Dragon Plateskirt",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Plateskirt, you should try it on!",
    type: "legs",
    prodTimer: 4,
    prodExp: 480,
    skill: "Smithing"
  },
  {
    itemID: 161,
    name: "Dragon Platebody",
    image: '../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A Dragon Platebody, you should try it on!",
    type: "chest",
    prodTimer: 4,
    prodExp: 800,
    skill: "Smithing"
  }
]

export default items