  const items = [
  {
    itemID: 1,
    name: "Coins",
    image: "coins.png",
    price: 1,
    haPrice: 0,
    description: "Coins!",
    type: "",
    prodTimer: null,
    prodExp: null
  },
  {
    itemID: 2,
    name: "Normal Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Normal_Log.png',
    price: 4,
    haPrice: 1,
    description: "Just normal logs.",
    type: "woodcutting",
    prodTimer: 1.5,
    prodExp: 15
  },
  {
    itemID: 3,
    name: "Oak logs",
    image: './../assets/ItemThumbnail/Woodcutting/Oak_Log.png',
    price: 8,
    haPrice: 3,
    description: "Pile of oak logs.",
    type: "woodcutting",
    prodTimer: 2,
    prodExp: 25
  },
  {
    itemID: 4,
    name: "Willow Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Willow_Log.png',
    price: 12,
    haPrice: 5,
    description: "Pile of willow logs.",
    type: "woodcutting",
    prodTimer: 3,
    prodExp: 40
  },
  {
    itemID: 5,
    name: "Maple Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Maple_Log.png',
    price: 16,
    haPrice: 8,
    description: "Pile of maple logs.",
    type: "woodcutting",
    prodTimer: 3.5,
    prodExp: 60
  },
  {
    itemID: 6,
    name: "Yew Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Yew_Log.png',
    price: 20,
    haPrice: 12,
    description: "Pile of yew logs.",
    type: "woodcutting",
    prodTimer: 5,
    prodExp: 75
  },
  {
    itemID: 7,
    name: "Magic Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Magic_Log.png',
    price: 30,
    haPrice: 15,
    description: "Pile of magic logs.",
    type: "woodcutting",
    prodTimer: 6,
    prodExp: 90
  },
  {
    itemID: 8,
    name: "Elder Logs",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 40,
    haPrice: 20,
    description: "Pile of elder logs.",
    type: "woodcutting",
    prodTimer: 8,
    prodExp: 120
  },
  {
    itemID: 9,
    name: "Shrimp",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 4,
    haPrice: 1,
    description: "A stack of shrimp, you should cook it.",
    type: "fishing",
    prodTimer: 2,
    prodExp: 15,
  },
  {
    itemID: 10,
    name: "Herring",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 6,
    haPrice: 2,
    description: "A herring, you should cook it.",
    type: "fishing",
    prodTimer: 2.5,
    prodExp: 25
  },
  {
    itemID: 11,
    name: "Trout",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 10,
    haPrice: 5,
    description: "A trout, you should cook it.",
    type: "fishing",
    prodTimer: 1.5,
    prodExp: 20,
  },
  {
    itemID: 12,
    name: "Pike",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 15,
    haPrice: 8,
    description: "A pike, you should cook it.",
    type: "fishing",
    prodTimer: 3,
    prodExp: 45
  },
  {
    itemID: 13,
    name: "Lobster",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 20,
    haPrice: 10,
    description: "A lobster, you should cook it.",
    type: "fishing",
    prodTimer: 5,
    prodExp: 75
  },
  {
    itemID: 14,
    name: "Swordfish",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 30,
    haPrice: 15,
    description: "A swordfish, you should cook it.",
    type: "fishing",
    prodTimer: 4,
    prodExp: 60
  },
  {
    itemID: 15,
    name: "Shark",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 40,
    haPrice: 25,
    description: "A shark, you should cook it.",
    type: "fishing",
    prodTimer: 6,
    prodExp: 100
  },
  {
    itemID: 16,
    name: "Manta Ray",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 50,
    haPrice: 30,
    description: "A manta ray, you should cook it.",
    type: "fishing",
    prodTimer: 6,
    prodExp: 120
  },
  {
    itemID: 17,
    name: "Dark Crab",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 60,
    haPrice: 40,
    description: "A dark crab, you should cook it.",
    type: "fishing",
    prodTimer: 8,
    prodExp: 150
  },
  {
    itemID: 18,
    name: "Tin Ore",
    image: './../assets/ItemThumbnail/Mining/Tin_Ore.png',
    price: 5,
    haPrice: 1,
    description: "Pile of Tin Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 3,
    prodExp: 20
  },
  {
    itemID: 19,
    name: "Copper Ore",
    image: './../assets/ItemThumbnail/Mining/Copper_Ore.png',
    price: 5,
    haPrice: 1,
    description: "Pile of Copper Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 3,
    prodExp: 20
  },
  {
    itemID: 20,
    name: "Iron Ore",
    image: './../assets/ItemThumbnail/Mining/Iron_Ore.png',
    price: 10,
    haPrice: 6,
    description: "Pile of Iron Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 1.5,
    prodExp: 15
  },
  {
    itemID: 21,
    name: "Coal Ore",
    image: './../assets/ItemThumbnail/Mining/Coal_Ore.png',
    price: 20,
    haPrice: 10,
    description: "Pile of Coal Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 5,
    prodExp: 45
  },
  {
    itemID: 22,
    name: "Silver Ore",
    image: './../assets/ItemThumbnail/Mining/Silver_Ore.png',
    price: 20,
    haPrice: 10,
    description: "Pile of Silver Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 4,
    prodExp: 40
  },
  {
    itemID: 23,
    name: "Gold Ore",
    image: './../assets/ItemThumbnail/Mining/Gold_Ore.png',
    price: 30,
    haPrice: 20,
    description: "Pile of Gold Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 5,
    prodExp: 55
  },
  {
    itemID: 24,
    name: "Mithril Ore",
    image: './../assets/ItemThumbnail/Mining/Mithril_Ore.png',
    price: 40,
    haPrice: 25,
    description: "Pile of Mithril Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 7,
    prodExp: 80
  },
  {
    itemID: 25,
    name: "Adamant Ore",
    image: './../assets/ItemThumbnail/Mining/Adamant_Ore.png',
    price: 50,
    haPrice: 35,
    description: "Pile of Adamant Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 8,
    prodExp: 90
  },
  {
    itemID: 26,
    name: "Rune Ore",
    image: './../assets/ItemThumbnail/Mining/Rune_Ore.png',
    price: 70,
    haPrice: 50,
    description: "Pile of Rune Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 10,
    prodExp: 150
  },
  {
    itemID: 27,
    name: "Dragon Ore",
    image: './../assets/ItemThumbnail/Mining/Dragon_Ore.png',
    price: 120,
    haPrice: 100,
    description: "Pile of Dragon Ore, you should try smelting it.",
    type: "mining",
    prodTimer: 12,
    prodExp: 200
  },
  {
    itemID: 28,
    name: "Bronze Bar",
    image: './../assets/ItemThumbnail/Smithing/Bronze_Bar.png',
    price: 20,
    haPrice: 10,
    description: "A solid Bronze Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 10
  },
  {
    itemID: 29,
    name: "Iron Bar",
    image: './../assets/ItemThumbnail/Smithing/Iron_Bar.png',
    price: 30,
    haPrice: 20,
    description: "A solid Iron Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 15
  },
  {
    itemID: 30,
    name: "Steel Bar",
    image: './../assets/ItemThumbnail/Smithing/Steel_Bar.png',
    price: 45,
    haPrice: 30,
    description: "A solid Steel Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 25
  },
  {
    itemID: 31,
    name: "Silver Bar",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 30,
    haPrice: 25,
    description: "A solid Silver Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 15
  },
  {
    itemID: 32,
    name: "Gold Bar",
    image: './../assets/ItemThumbnail/Woodcutting/Elder_Log.png',
    price: 45,
    haPrice: 35,
    description: "A solid Gold Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 25
  },
  {
    itemID: 33,
    name: "Mithril Bar",
    image: './../assets/ItemThumbnail/Smithing/Mithril_Bar.png',
    price: 100,
    haPrice: 60,
    description: "A solid Mithril Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 35
  },
  {
    itemID: 34,
    name: "Adamant Bar",
    image: './../assets/ItemThumbnail/Smithing/Adamant_Bar.png',
    price: 200,
    haPrice: 140,
    description: "A solid Adamant Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 50
  },
  {
    itemID: 35,
    name: "Rune Bar",
    image: './../assets/ItemThumbnail/Smithing/Rune_Bar.png',
    price: 400,
    haPrice: 320,
    description: "A solid Rune Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 60
  },
  {
    itemID: 36,
    name: "Dragon Bar",
    image: './../assets/ItemThumbnail/Smithing/Dragon_Bar.png',
    price: 760,
    haPrice: 640,
    description: "A solid Dragon Bar, you should try smithing it into something nice!",
    type: "smithing",
    prodTimer: 2,
    prodExp: 80
  }
]

export default items